#--------------------------------------------------------------------
#
# Developed by Andrey Dubovsky
#
# Script to Configure sudo for user habib without password prompt
#
# Tested on:
#           Ubuntu 24.04,
#           Fedora 40,
#           ArchLinux 6.11.1
#           Debian 12
#           RHEL 9.4
# Example: 
#
# ansible-playbook -i inventory.ini no_sudo_password.yml --ask-become-pass
#
#--------------------------------------------------------------------


---
- name: Configure sudo for user habib without password prompt
  hosts: all
  become: yes
  tasks:
    - name: Ensure sudoers file is configured for passwordless sudo for habib
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^habib ALL="
        line: "habib ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
